#%RAML 1.0
title: IaaS
# description: Instrumentation As A Service
version: v2
protocols: [http, https]
schemas:
  - error: !include schemas/error-schema.json
  - apk: !include schemas/apk-schema.json
  - apks: !include schemas/apks-schema.json
  - hash: !include schemas/hash-schema.json
  - metadata: !include schemas/metadata-schema.json
  - metadataList: !include schemas/metadataList-schema.json
/instrument:
  /withmetadata:
      post:
        description: |
          Instrument an apk file based on the configuration files attached
          to the request and store its logo, app name and package name in the database.
        body:
          multipart/form-data:
            formParameters:
              sourceFile:
                description: Source file containing the android's source methods
                displayName: Source File
                type: file
                required: true
              sinkFile:
                description: Sink file containing the android's sink methods
                displayName: Sink File
                type: file
                required: true
              easyTaintWrapperSource:
                description: |
                  Taint wrapper file containing the android's package names that
                  should be considered during the instrumentation phase
                displayName: Easy Taint Wrapper File
                type: file
                required: true
              apkFile:
                description: APK file that should be instrumented
                displayName: APK File
                type: file
                required: true
              logo:
                description: The logo of the app
                displayName: Logo
                type: file
                required: false
              appName:
                description: The name of the app
                displayName: App Name
                type: string
                required: false
              packagename:
                description: The packagename of the app
                displayName: Package Name
                type: string
                required: false
        responses:
          202:
            body:
              application/json:
                schema: apk
          400:
            body:
              application/json:
                schema: error
  /withoutmetadata:
    post:
      description: |
        Instrument an apk file based on the configuration files attached
        to the request
      body:
        multipart/form-data:
          formParameters:
            sourceFile:
              description: Source file containing the android's source methods
              displayName: Source File
              type: file
              required: true
            sinkFile:
              description: Sink file containing the android's sink methods
              displayName: Sink File
              type: file
              required: true
            easyTaintWrapperSource:
              description: |
                Taint wrapper file containing the android's package names that
                should be considered during the instrumentation phase
              displayName: Easy Taint Wrapper File
              type: file
              required: true
            apkFile:
              description: APK file that should be instrumented
              displayName: APK File
              type: file
              required: true
      responses:
        202:
          body:
            application/json:
              schema: apk
        400:
          body:
            application/json:
              schema: error
  /all:
    description: |
      A count and list of the SHA 512 hashes of all instrumented APKs
    get:
      description: Retrieve a list of instrumented apk files
      responses:
        200:
          body:
            application/json:
              schema: apks
  /{apkHash}:
    get:
      description: |
        Retrieve the binary dump of the instrumented apk file based on its hash sum value.
        The hash value is calculated from the non-instrumented apk with sha512.
      responses:
        200:
          body:
            multipart/form-data:
                    formParameters:
                        apkFile:
                            description: The instrumented APK file
                            displayName: APK File
                            type: file
                            required: true
        404:
          body:
            application/json:
              schema: error
/metadata:
  /all:
    description: |
      Get a list of all the metadata saved on the server.
    get:
      description: Retrieve a list of all the metadata of all instrumented apps
      responses:
        200:
          body:
            application/json:
              schema: metadataList
  /instrumented:
      description: |
        Get a list of the metadata saved on the server.
      get:
        description: Retrieve a list of all the metadata of all instrumented apps
        responses:
          200:
            body:
              application/json:
                schema: metadataList

  /logo/{apkHash}:
      get:
        description: |
          Retrieve the logo of the APK corresponding to the hash.
        responses:
          200:
            body:
              multipart/form-data:
                      formParameters:
                          logoFile:
                              description: The logo for the APK
                              displayName: Logo File
                              type: file
                              required: true
          404:
            body:
              application/json:
                schema: error